# Generated by Django 6.0.6 on 2026-06-08 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationReadingAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_water_level', models.FloatField()),
                ('min_water_level', models.FloatField()),
                ('max_water_level', models.FloatField()),
                ('std_deviation', models.FloatField(default=0.0)),
                ('confidence_score', models.FloatField(default=1.0)),
                ('reading_count', models.IntegerField()),
                ('time_window_start', models.DateTimeField()),
                ('time_window_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregates', to='stations.station')),
            ],
            options={
                'ordering': ['-time_window_end'],
            },
        ),
    ]
