# Generated by Django 6.0.6 on 2026-06-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_sensor_updated_at_station_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='sensor_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
