# Generated by Django 6.0.6 on 2026-06-09 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('stations', '0003_sensor_sensor_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='triggered_by',
            new_name='alert_type',
        ),
        migrations.AddField(
            model_name='alert',
            name='sensor',
            field=models.ForeignKey(default=34, on_delete=django.db.models.deletion.CASCADE, to='stations.sensor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alert',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station'),
        ),
    ]
