# Generated by Django 6.0.6 on 2026-08-17 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
